### ISSUE TITLE
iOS app store rejacted due to webview. how to use TwitterKit v5.1.0 in flutter

### ISSUE THREAD

**Issue by jerald-jacob** [touren/twitter-kit-ios#19]
One line summary of the issue here.

### Expected behavior

As concisely as possible, describe the expected behavior.

### Actual behavior

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by jerald-jacob** [comment]
all the packages are not performing a good result. plz help me to fix this issue. I'm using these two packages but the issue remain same.

https://pub.dev/packages/flutter_twitter_login

https://pub.dev/packages/flutter_twitter

**Comment by xzwgithub** [comment]
> all the packages are not performing a good result. plz help me to fix this issue. I'm using these two packages but the issue remain same.
> 
> https://pub.dev/packages/flutter_twitter_login
> 
> https://pub.dev/packages/flutter_twitter

You can edit the source code of Twitter and remove the code related to uiwebview. In fact, the source author has replaced uiwebview with wkwebview, but the word uiwebview may remain, causing apple to warn.

**Comment by xzwgithub** [comment]
> all the packages are not performing a good result. plz help me to fix this issue. I'm using these two packages but the issue remain same.
> 
> https://pub.dev/packages/flutter_twitter_login
> 
> https://pub.dev/packages/flutter_twitter

you can try my this twitter sdk, no UIWebView    https://github.com/xzwgithub/ios_twitterSdk_NO_UIWebView
