### ISSUE TITLE
Support for architecture arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by OmarJalil** [touren/twitter-kit-ios#27]
One line summary of the issue here.

### Expected behavior

TwitterCore should support arm64

### Actual behavior

building for iOS Simulator, but linking in dylib built for iOS, file '/Pods/TwitterKit5/iOS/TwitterKit.framework/TwitterKit' for architecture arm64

### Steps to reproduce the behavior

Just run on a M1 MacBook Pro on a Simulator

**Comment by alfonsocv12** [comment]
Have you try using [Swifter](https://github.com/mattdonnelly/Swifter)
