### ISSUE TITLE
cannot run ./build.sh

### ISSUE THREAD

**Issue by JoeSuen** [touren/twitter-kit-ios#5]
cannot run ./build.sh

### Expected behavior

get the zip

### Actual behavior

xcodebuild: error: SDK "iphonesimulator13.0" cannot be located.
xcodebuild: error: SDK "iphoneos13.0" cannot be located.
cp: TwitterKit/iphoneos/TwitterKit.framework/: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: TwitterKit/iphoneos/TwitterKit.framework/TwitterKit (No such file or directory)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: iOS/TwitterKit.framework/TwitterKit (No such file or directory)
rm: TwitterKit.zip: No such file or directory

### Steps to reproduce the behavior

cd rootfolder, and ./build.sh

**Comment by aliozinan** [comment]
please provide the output of :

`/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -version`

**Comment by touren** [comment]
It should be fixed in the most updated master branch. @JoeSuen
