### ISSUE TITLE
Opened Web TW Login after cancellation of Naive TW Login

### ISSUE THREAD

**Issue by woshiyezu** [touren/twitter-kit-ios#9]
Using TwitterKit5, showed Web TW login after cancelling Native TW login.

### Expected behavior

Come back app after cancelling Native TW login.

### Actual behavior

Opened Web TW Login after cancellation of Native TW Login

### Steps to reproduce the behavior

Just use TwitterKit5, open Native login and then cancel login on it.

**Comment by touren** [comment]
Can't reproduce in the Demo app within the project.

Check the code: https://github.com/touren/twitter-kit-ios/blob/master/TwitterKit/TwitterKit/TWTRTwitter.m#L380

Make sure using similar logic in your own method: (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary *)options

Ref: https://github.com/twitter-archive/twitter-kit-ios/issues/122

**Comment by woshiyezu** [comment]
Thanks. I will try it.

**Comment by fxsalazar** [comment]
I did test the DemoAPP out the box and _yes_, the WebView still poping up after app cancelation. I spotted an anomaly (made a PR #13); Still wondering why couldn't you reproduce the behaviour 🤔
